package errors

import (
	"reflect"
	"testing"
)

func TestFormatFileHeader(t *testing.T) {
	want := []string{
		"// Code generated by protoc-gen-sphere-errors. DO NOT EDIT.",
		"// versions:",
		"// - protoc             v5.29.0",
		"// source: errors.proto",
		"",
		"package errorsv1",
		"",
	}
	got := formatFileHeader("v5.29.0", "errors.proto", "errorsv1", false)
	if !reflect.DeepEqual(got, want) {
		t.Errorf("formatFileHeader() = %#v, want %#v", got, want)
	}

	deprecated := formatFileHeader("v5.29.0", "errors.proto", "errorsv1", true)
	if got, want := deprecated[3], "// errors.proto is a deprecated file."; got != want {
		t.Errorf("deprecated source line = %q, want %q", got, want)
	}
}
