package errors

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

// generateFileHeader writes the "DO NOT EDIT" banner, version comments and the
// package clause for the generated file.
func generateFileHeader(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	lines := formatFileHeader(
		protocVersion(gen),
		file.Desc.Path(),
		string(file.GoPackageName),
		file.Proto.GetOptions().GetDeprecated(),
	)
	for _, line := range lines {
		g.P(line)
	}
}

// protocVersion returns the formatted compiler version from the generator request.
func protocVersion(gen *protogen.Plugin) string {
	return formatProtocVersion(gen.Request.GetCompilerVersion())
}

// formatProtocVersion formats a compiler version as e.g. "v5.29.0" or
// "(unknown)" when no version is provided.
func formatProtocVersion(v *pluginpb.Version) string {
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

// formatFileHeader builds the standard generated-file header, including the
// package declaration.
func formatFileHeader(version, sourcePath, pkgName string, deprecated bool) []string {
	lines := []string{
		"// Code generated by protoc-gen-sphere-errors. DO NOT EDIT.",
		"// versions:",
		fmt.Sprintf("// - protoc             %s", version),
	}
	if deprecated {
		lines = append(lines, fmt.Sprintf("// %s is a deprecated file.", sourcePath))
	} else {
		lines = append(lines, fmt.Sprintf("// source: %s", sourcePath))
	}
	return append(lines, "", fmt.Sprintf("package %s", pkgName), "")
}
