package errors

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

// generateFileHeader writes the "DO NOT EDIT" banner, version comments and the
// package clause for the generated file.
func generateFileHeader(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	g.P("// Code generated by protoc-gen-sphere-errors. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
}

// protocVersion returns the formatted compiler version from the generator request.
func protocVersion(gen *protogen.Plugin) string {
	return formatProtocVersion(gen.Request.GetCompilerVersion())
}

// formatProtocVersion formats a compiler version as e.g. "v5.29.0" or
// "(unknown)" when no version is provided.
func formatProtocVersion(v *pluginpb.Version) string {
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}
