// Code generated by protoc-gen-sphere-errors. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: alias_errors.proto

package alias

import (
	errors "errors"
	httpx "github.com/go-sphere/httpx"
)

func (e AliasError) Error() string {
	switch e {
	case AliasError_ALIAS_ERROR_UNSPECIFIED:
		return "AliasError:ALIAS_ERROR_UNSPECIFIED"
	case AliasError_ALIAS_ERROR_INVALID:
		return "invalid request"
	default:
		return "AliasError:UNKNOWN_ERROR"
	}
}

func (e AliasError) GetCode() int32 {
	switch e {
	case AliasError_ALIAS_ERROR_UNSPECIFIED:
		return 0
	case AliasError_ALIAS_ERROR_INVALID:
		return 1
	default:
		return 0
	}
}

func (e AliasError) GetStatus() int32 {
	switch e {
	case AliasError_ALIAS_ERROR_UNSPECIFIED:
		return 400
	case AliasError_ALIAS_ERROR_INVALID:
		return 400
	default:
		return 500
	}
}

func (e AliasError) GetMessage() string {
	switch e {
	case AliasError_ALIAS_ERROR_UNSPECIFIED:
		return ""
	case AliasError_ALIAS_ERROR_INVALID:
		return "the request is invalid"
	default:
		return ""
	}
}

func (e AliasError) Join(errs ...error) error {
	allErrs := append([]error{e}, errs...)
	msg := e.GetMessage()
	if msg == "" {
		msg = e.Error()
	}
	return httpx.NewError(
		e.GetStatus(),
		e.GetCode(),
		msg,
		errors.Join(allErrs...),
	)
}

func (e AliasError) JoinWithMessage(msg string, errs ...error) error {
	allErrs := append([]error{e}, errs...)
	return httpx.NewError(
		e.GetStatus(),
		e.GetCode(),
		msg,
		errors.Join(allErrs...),
	)
}
