// Code generated by protoc-gen-sphere-errors. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: basic_errors.proto

package basic

import (
	errors "errors"
	httpx "github.com/go-sphere/httpx"
)

func (e UserError) Error() string {
	switch e {
	case UserError_USER_ERROR_UNSPECIFIED:
		return "UserError:USER_ERROR_UNSPECIFIED"
	case UserError_USER_ERROR_INVALID_ID:
		return "invalid user id"
	case UserError_USER_ERROR_NOT_FOUND:
		return "user not found"
	case UserError_USER_ERROR_PERMISSION_DENIED:
		return "permission denied"
	case UserError_USER_ERROR_DEFAULTED:
		return "UserError:USER_ERROR_DEFAULTED"
	default:
		return "UserError:UNKNOWN_ERROR"
	}
}

func (e UserError) GetCode() int32 {
	switch e {
	case UserError_USER_ERROR_UNSPECIFIED:
		return 0
	case UserError_USER_ERROR_INVALID_ID:
		return 1
	case UserError_USER_ERROR_NOT_FOUND:
		return 2
	case UserError_USER_ERROR_PERMISSION_DENIED:
		return 3
	case UserError_USER_ERROR_DEFAULTED:
		return 4
	default:
		return 0
	}
}

func (e UserError) GetStatus() int32 {
	switch e {
	case UserError_USER_ERROR_UNSPECIFIED:
		return 400
	case UserError_USER_ERROR_INVALID_ID:
		return 400
	case UserError_USER_ERROR_NOT_FOUND:
		return 404
	case UserError_USER_ERROR_PERMISSION_DENIED:
		return 403
	case UserError_USER_ERROR_DEFAULTED:
		return 400
	default:
		return 500
	}
}

func (e UserError) GetMessage() string {
	switch e {
	case UserError_USER_ERROR_UNSPECIFIED:
		return ""
	case UserError_USER_ERROR_INVALID_ID:
		return "invalid user ID format"
	case UserError_USER_ERROR_NOT_FOUND:
		return "user does not exist"
	case UserError_USER_ERROR_PERMISSION_DENIED:
		return ""
	case UserError_USER_ERROR_DEFAULTED:
		return ""
	default:
		return ""
	}
}

func (e UserError) Join(errs ...error) error {
	allErrs := append([]error{e}, errs...)
	msg := e.GetMessage()
	if msg == "" {
		msg = e.Error()
	}
	return httpx.NewError(
		e.GetStatus(),
		e.GetCode(),
		msg,
		errors.Join(allErrs...),
	)
}

func (e UserError) JoinWithMessage(msg string, errs ...error) error {
	allErrs := append([]error{e}, errs...)
	return httpx.NewError(
		e.GetStatus(),
		e.GetCode(),
		msg,
		errors.Join(allErrs...),
	)
}

func (e OrderError) Error() string {
	switch e {
	case OrderError_ORDER_ERROR_UNSPECIFIED:
		return "OrderError:ORDER_ERROR_UNSPECIFIED"
	case OrderError_ORDER_ERROR_OUT_OF_STOCK:
		return "out of stock"
	default:
		return "OrderError:UNKNOWN_ERROR"
	}
}

func (e OrderError) GetCode() int32 {
	switch e {
	case OrderError_ORDER_ERROR_UNSPECIFIED:
		return 0
	case OrderError_ORDER_ERROR_OUT_OF_STOCK:
		return 1
	default:
		return 0
	}
}

func (e OrderError) GetStatus() int32 {
	switch e {
	case OrderError_ORDER_ERROR_UNSPECIFIED:
		return 500
	case OrderError_ORDER_ERROR_OUT_OF_STOCK:
		return 400
	default:
		return 500
	}
}

func (e OrderError) GetMessage() string {
	switch e {
	case OrderError_ORDER_ERROR_UNSPECIFIED:
		return ""
	case OrderError_ORDER_ERROR_OUT_OF_STOCK:
		return "product is out of stock"
	default:
		return ""
	}
}

func (e OrderError) Join(errs ...error) error {
	allErrs := append([]error{e}, errs...)
	msg := e.GetMessage()
	if msg == "" {
		msg = e.Error()
	}
	return httpx.NewError(
		e.GetStatus(),
		e.GetCode(),
		msg,
		errors.Join(allErrs...),
	)
}

func (e OrderError) JoinWithMessage(msg string, errs ...error) error {
	allErrs := append([]error{e}, errs...)
	return httpx.NewError(
		e.GetStatus(),
		e.GetCode(),
		msg,
		errors.Join(allErrs...),
	)
}
