// Code generated by protoc-gen-sphere-errors. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: mixed_enums.proto

package mixed

import (
	errors "errors"
	httpx "github.com/go-sphere/httpx"
)

func (e AuthError) Error() string {
	switch e {
	case AuthError_AUTH_ERROR_UNSPECIFIED:
		return "AuthError:AUTH_ERROR_UNSPECIFIED"
	case AuthError_AUTH_ERROR_TOKEN_EXPIRED:
		return "token expired"
	default:
		return "AuthError:UNKNOWN_ERROR"
	}
}

func (e AuthError) GetCode() int32 {
	switch e {
	case AuthError_AUTH_ERROR_UNSPECIFIED:
		return 0
	case AuthError_AUTH_ERROR_TOKEN_EXPIRED:
		return 1
	default:
		return 0
	}
}

func (e AuthError) GetStatus() int32 {
	switch e {
	case AuthError_AUTH_ERROR_UNSPECIFIED:
		return 401
	case AuthError_AUTH_ERROR_TOKEN_EXPIRED:
		return 401
	default:
		return 500
	}
}

func (e AuthError) GetMessage() string {
	switch e {
	case AuthError_AUTH_ERROR_UNSPECIFIED:
		return ""
	case AuthError_AUTH_ERROR_TOKEN_EXPIRED:
		return "the access token has expired"
	default:
		return ""
	}
}

func (e AuthError) Join(errs ...error) error {
	allErrs := append([]error{e}, errs...)
	msg := e.GetMessage()
	if msg == "" {
		msg = e.Error()
	}
	return httpx.NewError(
		e.GetStatus(),
		e.GetCode(),
		msg,
		errors.Join(allErrs...),
	)
}

func (e AuthError) JoinWithMessage(msg string, errs ...error) error {
	allErrs := append([]error{e}, errs...)
	return httpx.NewError(
		e.GetStatus(),
		e.GetCode(),
		msg,
		errors.Join(allErrs...),
	)
}
